name: Rando

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        DB_HOST: db
        MIX_ENV: test
    container: 
      image: elixir:1.14.0-alpine
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        run: |
          apk --no-cache --update add alpine-sdk
          mix local.rebar --force
          mix local.hex --force
      - name: Install dependencies
        run: |
            mix deps.get
            mix compile
      - name: Lint
        run: mix format --check-formatted 
      - name: Credo
        run: mix credo
      - name: Dialyzer 
        run: mix dialyzer --list-unused-filters --force-check
      - name: Test
        run: mix test
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('mix.lock') }}

   